import streamlit as st
import pandas as pd
import joblib
from pathlib import Path
import os

# Resolving paths robustly without circular imports
DASHBOARD_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = DASHBOARD_DIR.parent
MODELS_DIR = PROJECT_ROOT / "models"
TRAINED_MODELS_DIR = MODELS_DIR / "trained_models"
OUTPUTS_DIR = PROJECT_ROOT / "outputs"
PREDICTIONS_PATH = OUTPUTS_DIR / "predictions.parquet"
BEST_MODEL_PATH = TRAINED_MODELS_DIR / "best_model.pkl"

@st.cache_resource
def load_model():
    """
    Loads the real trained LightGBM model from disk.
    Cached as a resource to prevent reloading on every interaction.
    """
    model_path = BEST_MODEL_PATH
    if not model_path.exists():
        st.error(f"❌ Model file not found at: {model_path}\nPlease run 'python run_pipeline.py' first.")
        st.stop()
    try:
        return joblib.load(model_path)
    except Exception as e:
        st.error(f"❌ Failed to load model: {str(e)}")
        st.stop()

@st.cache_data
def load_processed_data():
    """
    Loads the REAL predictions dataset generated by the inference engine.
    Strictly prevents fallback to synthetic/fake data.
    """
    if not PREDICTIONS_PATH.exists():
        st.error(f"❌ Predictions artifact not found at: {PREDICTIONS_PATH}\nPlease run 'python run_pipeline.py' to orchestrate the pipeline.")
        st.stop()
        
    try:
        df = pd.read_parquet(PREDICTIONS_PATH)
        
        # Strict validation of required inference schema
        required_cols = ['TransactionID', 'TransactionAmt', 'prediction_probability', 'Risk_Tier', 'isFraud']
        missing_cols = [col for col in required_cols if col not in df.columns]
        if missing_cols:
            st.error(f"❌ Predictions artifact missing required schema columns: {missing_cols}")
            st.stop()
            
        return df
    except Exception as e:
        st.error(f"❌ Failed to load predictions data: {str(e)}")
        st.stop()
